/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.hibernate.engine {

    [Bindable]
    [RemoteClass(alias="org.hibernate.engine.BatchFetchQueue")]
    public class BatchFetchQueue extends BatchFetchQueueBase {
    }
}