INSERT INTO TIPO_ARQUIVO (DS_TIPO_ARQUIVO) VALUES ('SQL');
INSERT INTO TIPO_ARQUIVO (DS_TIPO_ARQUIVO) VALUES ('TXT');

INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('SERIAL', '0', '2147483647');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('BOOLEAN', '0', '1');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('DOUBLE', '-1.7976931348623157E+308', '2250738585072014E-308');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('DECIMAL', '0', '255');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('INTEGER', '-2147483647', '2147483647');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('NUMERIC', '0', '255');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('DATE', '10', '10');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('TIMESTAMP', '2', '14');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('TIME', '9', '9');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('CHAR', '0', '255');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('VARCHAR', '0', '255');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('BIT', '0', '1');
INSERT INTO TIPO_CAMPO (DS_TIPO_CAMPO, DS_VALOR_MINIMO, DS_VALOR_MAXIMO) VALUES ('BLOB', '0', '65535');

INSERT INTO TIPO_TABELA (DS_TIPO_TABELA) VALUES ('MyISAM');
INSERT INTO TIPO_TABELA (DS_TIPO_TABELA) VALUES ('MERGE');
INSERT INTO TIPO_TABELA (DS_TIPO_TABELA) VALUES ('ISAM');
INSERT INTO TIPO_TABELA (DS_TIPO_TABELA) VALUES ('HEAP');
INSERT INTO TIPO_TABELA (DS_TIPO_TABELA) VALUES ('InnoDB');
INSERT INTO TIPO_TABELA (DS_TIPO_TABELA) VALUES ('BDB');
INSERT INTO TIPO_TABELA (DS_TIPO_TABELA) VALUES ('BerkeleyDB');